### ISSUE TITLE
Periodically disconnects with mosquitto 1.4.15

### ISSUE THREAD

**Issue by Hacker-CB** [wialon/gmqtt#110]
Hello!

I'm using your clean example from README and I have two problems:

- Client periodically disconnects (around every 30 seconds)
- Clean session does not work after reconnecting and I receive messages for old subscription which I made before with the same client ID. 

```
Connected
[TRYING WRITE TO CLOSED SOCKET]
Disconnected
Connected
Disconnected
[TRYING WRITE TO CLOSED SOCKET]
Connected
[TRYING WRITE TO CLOSED SOCKET]
Disconnected
Connected
[TRYING WRITE TO CLOSED SOCKET]
Disconnected
Connected
[TRYING WRITE TO CLOSED SOCKET]
Disconnected
Connected
Disconnected
```

**mosquitto**: 1.4.15
**gmqtt**: 0.6.5

With mosquitto 1.6.9 all works fine.

**Comment by Mixser** [comment]
Hello, @Hacker-CB 

Thanks for your interesting in our project. At first look, I think this is a problem of _mosquitto_ rather than problem of _gmqtt_. But we will check this behavior.

PS: Please look the issue #103, and send us detailed logs of your app and mosquitto

**Comment by Hacker-CB** [comment]
Seems that problem was that I had two clients with the same client ID.
So, problem with disconnections was from there.

Thank you.
