### ISSUE TITLE
Test requirements are incorrectly bundled in with install requirements

### ISSUE THREAD

**Issue by skewty** [wialon/gmqtt#29]
Can you please separate your test requirements and install requirements?  Currently they are both combined in requirements.txt.

[See here](https://stackoverflow.com/questions/4734292/specifying-where-to-install-tests-require-dependencies-of-a-distribute-setupto)

[And here](https://packaging.python.org/discussions/install-requires-vs-requirements/)

**Comment by Lenka42** [comment]
@skewty thanks for this issue, I made test dependencies more explicit
