### ISSUE TITLE
Connection error: [CONNACK] 0x1 Task exception was never retrieved

### ISSUE THREAD

**Issue by Snevzor** [wialon/gmqtt#31]
Hello,

I cannot get the examples to work. 

I've stripped a publish example down to:
```
import asyncio

from gmqtt import Client as MQTTClient

TOPIC = 'testtopic/TOPIC'


def on_connect(client, flags, rc, properties):
    print('Connected')


async def main(broker_host):
    client = MQTTClient(None)
    client.on_connect = on_connect
    await client.connect(broker_host, keepalive=60)
    client.publish(TOPIC, 'Message payload')
    await client.disconnect()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()

    loop.run_until_complete(main("127.0.0.1"))
```
A broker is running on localhost.

Python version 3.5.2.

**Comment by Snevzor** [comment]
Perhaps I'm lacking some MQTT V5 knowledge. It works with V4.

**Comment by Lenka42** [comment]
@Snevzor  I think, error occurred  because your broker does not support MQTT 5.0 version 
`0x01 Connection Refused, unacceptable protocol version`

**Comment by Snevzor** [comment]
Thanks for the fast response @Lenka42. That was exactly the problem.
