### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by Snevzor** [wialon/gmqtt#50]
Could it be possible to make the extensive logging optional?

**Comment by Mixser** [comment]
Hi @Snevzor, 
If you don't need to get gmqtt's logs, you may switch off them by adding this in as early you can:
```
logging.getLogger('gmqtt').setLevel(logging.ERROR)
```

And you will receive only logs about errors.

**Comment by Snevzor** [comment]
Thanks Mixser!
