### ISSUE TITLE
How do you subscribe to multiple topics ?

### ISSUE THREAD

**Issue by rajdeeprath** [wialon/gmqtt#51]

**Comment by Lenka42** [comment]
@rajdeeprath right now gmqtt does not allow to subscribe to multiple topics in one packet. But I also think this might be a useful feature, so if you want, you may create a PR :smile: Or I will start work on this in a few days or weeks :thinking:

**Comment by Lenka42** [comment]
@rajdeeprath Now you can subscribe to multiple topics in one command: 
```
client.subscribe([gmqtt.Subscription('TEST/+', qos=1), gmqtt.Subscription('TEST', qos=0)],                   
                 subscription_identifier=1)
```
Please upgrade to gmqtt==0.4.0
