### ISSUE TITLE
async handle task.cancel()

### ISSUE THREAD

**Issue by nicola-lunghi** [wialon/gmqtt#73]
Hi,
in all of the example this library is used with an asyncio event() to handle the termination of the library.
How can I handle instead an asyncio coroutine?

I have multiple tasks that are running in parallel with asyncio.gather()

this is another one

```

async def mqtt_consumer(mqtt_queue):
    logger.info('Starting consumer')

    try:
        while True:
            logger.info('Waiting for message')
            msg = await mqtt_queue.get()
            print(f"Got {msg}")
    except asyncio.CancelledError:
        pass
    finally:
        logger.info('Exiting consumer')
```

```
try:
        loop.run_until_complete(tasks)
except KeyboardInterrupt as e:
     tasks.cancel()
     loop.run_forever()
finally:
     loop.close()
     logging.info("Successfully shutdown the services.")
```

How can I run gmqtt in a while True await?

**Comment by Lenka42** [comment]
I don't understand waht you are asking about. `tasks.cancel()` should work, does this work in your case? But this is a bad practice, it's better to stop client gently calling `client.disconnect()` 
It does not matter whether you catch `except asyncio.CancelledError` or wait for some event or varriable set.

**Comment by Lenka42** [comment]
@nicola-lunghi  I will close the issue. If you have further questions, please reopen.
