### ISSUE TITLE
How to connect to username/password protected broker

### ISSUE THREAD

**Issue by leantw1ce** [wialon/gmqtt#94]
Hi, 
I'm new to mqtt. After cloning the repo I managed to make the "Getting started" code work. My question is, how can I connect to protected brokers with a simple username and password? I have no idea what to edit and where. 

Thanks!

**Comment by Lenka42** [comment]
@leantw1ce Hi!
try this way:
```
client = MQTTClient("client-id")
...
# this should be done before connect is called
client.set_auth_credentials(username, password)
...
await client.connect(broker_host)
```

**Comment by Lenka42** [comment]
@leantw1ce I'm closing this isuue, if you have any other questions or something is not working properly, feel free to reopen.
