### ISSUE TITLE
restore subscriptions after connection lost

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [wialon/gmqtt#97]
Hi,
I'm facing an issue when restoring subscriptions after a lost connection. I'm testing durability of connections and whenever I shut the connection down (turning the access point off) gmqtt reconnects and delivers messages but the subscriptions remain dead.

I see two of the following log messages right after each other:
```
INFO:mqtt.MQTTClient:MQTT connected
INFO:gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
WARNING:gmqtt.mqtt.handler:[EXC OCCURED] in reconnect future None
```
A little later:
```
INFO:gmqtt.mqtt.protocol:[CONNECTION MADE]
WARNING:gmqtt.mqtt.handler:[EXC OCCURED] in reconnect future None
```
Any idea on how to either verify subscriptions and resubscribe in case a subscription is lost or how to make subscriptions more robust?

**Comment by HerrMuellerluedenscheid** [comment]
Turns out that the subscriptions it not established in the first place. I'm using an asyncio routine for that which is waiting for the connection to be established inside of a `MQTTClient` subclass:

```
await self._connected.wait()
self.subscribe(topic, qos=qos)
```

The subscription happens right before the connection crashes (see above). But after the connection is lost, no message go through to the subscription.

**Comment by miili** [comment]
The exception is also due to this https://github.com/wialon/gmqtt/commit/90766b0d8c009ddbdec94180f906f975ce92b435#r36865808 in v0.5.5.

**Comment by Lenka42** [comment]
@HerrMuellerluedenscheid `WARNING:gmqtt.mqtt.handler:[EXC OCCURED] in reconnect future None` is buggy logging :disappointed: as @miili mentioned. Today new version`0.6.0` is released, it's fixed there. 
Wether subscriptions are alive or not depends on the session life time. You can manipulate session with parameters `clean_session` parameter and `sssion_expiry_interval` connect property.

**Comment by Lenka42** [comment]
@HerrMuellerluedenscheid I will close the issue. If you have further questions, please reopen.
